In [6]:
#creating numpy array with custom values and pattern
import numpy as np
num=int(input("Enter any number\n"))
arr1=np.zeros((3,4),dtype=np.int8)
print(arr1)
for i in range(3):
    temp=(i+1)*num
    for j in range(4):
        arr1[i][j]=temp
        temp=temp+1
print(arr1)

Enter any number
5
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]


In [10]:
#Selection by integer location
import pandas as pd1
import pandas as pd1
data1 = [{'x': 1, 'y': 2},{'x': 5, 'y': 4,'z': 5}]
df1 = pd1.DataFrame(data1,index=['one','two'])
df1.loc['three'] = 2*df1.loc['one']
print (df1.iloc[2])

x    2.0
y    4.0
z    NaN
Name: three, dtype: float64


In [11]:
from pandas import DataFrame
employees = [{'firstName': 'Rahul', 'lastName': 'Anand', 'age':26},
                 {'firstName': 'Sandeep', 'lastName': 'Kulkarni', 'age':25},
                 {'firstName': 'Daniel', 'lastName': 'Charles', 'age':32}]
df = DataFrame(employees);
print(df)
print('*********')
    
#iterate all rows
for index, row in df.iterrows() :
    print('Data at index', index)
    print(row)
    
print('*********')

#get specific column(firstName)
print('\n*** FirstName ***')
for index, row in df.iteritems() :
    print(row[1])

   age firstName  lastName
0   26     Rahul     Anand
1   25   Sandeep  Kulkarni
2   32    Daniel   Charles
*********
Data at index 0
age             26
firstName    Rahul
lastName     Anand
Name: 0, dtype: object
Data at index 1
age                25
firstName     Sandeep
lastName     Kulkarni
Name: 1, dtype: object
Data at index 2
age               32
firstName     Daniel
lastName     Charles
Name: 2, dtype: object
*********

*** FirstName ***
25
Sandeep
Kulkarni


In [13]:
from pandas import DataFrame
employees = [{'firstName': 'Rahul', 'lastName': 'Anand', 'age':26},
                 {'firstName': 'Sandeep', 'lastName': 'Kulkarni', 'age':25},
                 {'firstName': 'Daniel', 'lastName': 'Charles', 'age':32}]
df = DataFrame(employees);
print(df.firstName)

0      Rahul
1    Sandeep
2     Daniel
Name: firstName, dtype: object
