In [4]:
import pandas as pd1
s = pd1.Series([10,2,3,4,5],index = ['a','b','c','d','e'])
#print (s[0])# for 0 index position
#print (s[:3]) #for first 3 index values
print (s[-3:]) #for last 3 index values

c    3
d    4
e    5
dtype: int64


In [5]:
import pandas as pd1
s = pd1.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print (s[['c','d']])

c    3
d    4
dtype: int64


In [6]:
import pandas as pd1
s = pd1.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print (s.tail(1))

e    5
dtype: int64


In [1]:
print(''.join(s[0].upper() + '.' for s in "as far as i know".split()))

A.F.A.I.K.


In [2]:
data=[[1,2],[3,4]]
print(type(data))

<class 'list'>


In [3]:
from scipy import misc
import pylab as plt
face = misc.face(gray=True)
plt.imshow(face)

In [13]:
import pandas as pd
import numpy as np
obj1=pd.Series([20,22,24,26,20,25,28])
obj2=pd.Series([27,29,28,26,27,22,20])
obj3=pd.Series([22,25,26,21,29,24,28])
obj4=pd.Series([30,29,32,26,27,32,29])
#print(obj1)
#print(obj2)
#print(obj3)
#print(obj4)
sum2=0
for i in obj1:
    sum2=sum2+i
print(sum2/7)

sum1=np.sum(obj1)
print(sum1)

23.571428571428573
165


In [16]:
import numpy as np
b=np.arange(16).reshape(4,4)
print(b)
#b.reshape(4,4)
#print(b)
a = np.arange(25).reshape(5, 5)
#print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
